### ISSUE TITLE
[Docker Warrior] No usable Wget+At found

### ISSUE THREAD

**Issue by TSRBerry** [ArchiveTeam/reddit-grab#9]
Hello,

I just checked my warrior docker container and saw that it wasn't working on anything, although I selected the "ArchiveTeams's Choice" project. Looking at the logs there seems to be an issue with this project:

```
2021-10-11 00:34:24,409 - seesaw.warrior - DEBUG - Update warrior hq.
2021-10-11 00:34:24,409 - seesaw.warrior - DEBUG - Warrior ID ''.
2021-10-11 00:34:24,659 - seesaw.warrior - DEBUG - Select project reddit
2021-10-11 00:34:24,659 - seesaw.warrior - DEBUG - Start selected project reddit (reinstall=False)
2021-10-11 00:34:24,659 - seesaw.warrior - DEBUG - Check project has update reddit
2021-10-11 00:34:24,663 - seesaw.warrior - DEBUG - git fetch
2021-10-11 00:34:24,974 - seesaw.warrior - DEBUG - False
2021-10-11 00:34:24,975 - seesaw.warrior - DEBUG - Clone project reddit /home/warrior/projects/reddit
2021-10-11 00:34:24,978 - seesaw.warrior - DEBUG - Cloning version 8a3f8cd
2021-10-11 00:34:24,979 - seesaw.warrior - DEBUG - Load pipeline /home/warrior/data/projects/reddit-8a3f8cd/pipeline.py
2021-10-11 00:34:24,979 - seesaw.warrior - DEBUG - Pipeline has been read. Begin ConfigValue collection
2021-10-11 00:34:24,979 - seesaw.warrior - DEBUG - Executing pipeline
2021-10-11 00:34:24,990 - seesaw.warrior - ERROR - Error loading pipeline
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/seesaw/warrior.py", line 736, in start_selected_project
    (project, pipeline, config_values) = self.load_pipeline(
  File "/usr/local/lib/python3.9/site-packages/seesaw/warrior.py", line 686, in load_pipeline
    exec(pipeline_str, local_context, global_context)
  File "<string>", line 54, in <module>
Exception: No usable Wget+At found.
2021-10-11 00:34:24,990 - seesaw.warrior - WARNING - Project reddit did not install correctly and we're ignoring this problem.
2021-10-11 00:38:28,470 - seesaw.warrior - INFO - Runner has finished.
2021-10-11 00:44:24,409 - seesaw.warrior - DEBUG - Update warrior hq.
2021-10-11 00:44:24,409 - seesaw.warrior - DEBUG - Warrior ID ''.
2021-10-11 00:44:24,518 - seesaw.warrior - DEBUG - Update project.
2021-10-11 00:44:24,518 - seesaw.warrior - DEBUG - Check project has update reddit
2021-10-11 00:44:24,520 - seesaw.warrior - DEBUG - git fetch
2021-10-11 00:44:24,645 - seesaw.warrior - DEBUG - Select project reddit
2021-10-11 00:44:24,794 - seesaw.warrior - DEBUG - False
2021-10-11 00:54:24,409 - seesaw.warrior - DEBUG - Update warrior hq.
2021-10-11 00:54:24,409 - seesaw.warrior - DEBUG - Warrior ID ''.
2021-10-11 00:54:24,628 - seesaw.warrior - DEBUG - Select project reddit
2021-10-11 09:45:38,332 - root - INFO - Logging to /home/warrior/data/warrior.log
2021-10-11 09:45:38,337 - seesaw.warrior - DEBUG - Update warrior hq.
2021-10-11 09:45:38,338 - seesaw.warrior - DEBUG - Warrior ID ''.
2021-10-11 09:45:38,747 - seesaw.warrior - DEBUG - Select project reddit
2021-10-11 09:45:38,747 - seesaw.warrior - DEBUG - Start selected project reddit (reinstall=False)
2021-10-11 09:45:38,747 - seesaw.warrior - DEBUG - Install project reddit
2021-10-11 09:45:38,765 - seesaw.warrior - DEBUG - git pull from https://github.com/ArchiveTeam/reddit-grab
2021-10-11 09:45:39,299 - seesaw.warrior - DEBUG - git operation: Already up to date.
2021-10-11 09:45:39,300 - seesaw.warrior - DEBUG - Install complete Already up to date.
2021-10-11 09:45:39,300 - seesaw.warrior - DEBUG - Result of the install process: True
2021-10-11 09:45:39,300 - seesaw.warrior - DEBUG - Clone project reddit /home/warrior/projects/reddit
2021-10-11 09:45:39,304 - seesaw.warrior - DEBUG - Cloning version 8a3f8cd
2021-10-11 09:45:39,304 - seesaw.warrior - DEBUG - Load pipeline /home/warrior/data/projects/reddit-8a3f8cd/pipeline.py
2021-10-11 09:45:39,305 - seesaw.warrior - DEBUG - Pipeline has been read. Begin ConfigValue collection
2021-10-11 09:45:39,305 - seesaw.warrior - DEBUG - Executing pipeline
2021-10-11 09:45:39,417 - seesaw.warrior - ERROR - Error loading pipeline
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/seesaw/warrior.py", line 736, in start_selected_project
    (project, pipeline, config_values) = self.load_pipeline(
  File "/usr/local/lib/python3.9/site-packages/seesaw/warrior.py", line 686, in load_pipeline
    exec(pipeline_str, local_context, global_context)
  File "<string>", line 54, in <module>
Exception: No usable Wget+At found.
2021-10-11 09:45:39,419 - seesaw.warrior - WARNING - Project reddit did not install correctly and we're ignoring this problem.
2021-10-11 09:55:38,338 - seesaw.warrior - DEBUG - Update warrior hq.
2021-10-11 09:55:38,338 - seesaw.warrior - DEBUG - Warrior ID ''.
2021-10-11 09:55:39,833 - seesaw.warrior - DEBUG - Select project reddit
2021-10-11 10:05:38,338 - seesaw.warrior - DEBUG - Update warrior hq.
2021-10-11 10:05:38,338 - seesaw.warrior - DEBUG - Warrior ID ''.
```

I also checked my other machine which is running with the same configuration and it had the same issue. But on that machine I was able to solve it by stopping the container, removing it, deleting the mounted volume and creating a new one. Then I just had to choose another project, wait for a few minutes and was able to use this project again.

I have no clue how this is related and if this description provides any valuable information for you. But I included it just in case it does help you somehow.

**Comment by Arkiver2** [comment]
Does this problem still exist?

**Comment by jeliebig** [comment]
I think it had something to do with me using a docker volume with the warrior container.

A few months ago was the last time where I had to manually delete the project from my docker volume and re-download it to fix it. 

I did not run into it for a while now, so I think it might have been some update, that didn't copy all the files to the volume.
